spring:
  application:
    name: product-service-local
  
  datasource:
    url: jdbc:h2:mem:localdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      data-locations: classpath:db/test-data.sql

# JWT Configuration
jwt:
  secret: your-secret-key-for-jwt-token-must-be-at-least-256-bits

server:
  port: 8082

eureka:
  client:
    enabled: false

logging:
  level:
    com.sangsangplus.productservice: DEBUG