apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: product-service
data:
  application.yml: |
    spring:
      profiles:
        active: k8s
      application:
        name: product-service
      datasource:
        url: jdbc:postgresql://sangsangplus-postgre-server.postgres.database.azure.com:5432/product_db?sslmode=require
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        hikari:
          connection-timeout: 30000
          maximum-pool-size: 10
      azure:
        eventhub:
          producer:
            connection-string: ${PRODUCT_EVENTHUB_CONNECTION_STRING}
            name: product-events
          consumer:
            connection-string: ${USER_EVENTHUB_CONNECTION_STRING}
            name: user-events
            consumer-group: product-service-group
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://gateway-service:8080
              jwk-set-uri: http://gateway-service:8080/.well-known/jwks.json
    
    server:
      port: 8082
    
    eureka:
      client:
        enabled: false