apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: sangsangplus-backend
  labels:
    app: product-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: buildingbite/sangsangplus-product:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=50.0 -Djava.security.egd=file:/dev/./urandom"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: product-service-secret
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-service-secret
              key: db-password
        - name: PRODUCT_EVENTHUB_CONNECTION_STRING
          value: "Endpoint=sb://sangsangplus-eventhubs.servicebus.windows.net/;SharedAccessKeyName=ProductProducerKey;SharedAccessKey=/vg3jpxHFMdRPpuSGlya7nHBphlbzCRwt+AEhFV6Q2M=;EntityPath=product-events"
        - name: USER_EVENTHUB_CONNECTION_STRING
          value: "Endpoint=sb://sangsangplus-eventhubs.servicebus.windows.net/;SharedAccessKeyName=UserConsumerKey;SharedAccessKey=ZPRtTjEQZ9Wi4VoKiyNeViYVjvMvtBHdG+AEhCTFjGI=;EntityPath=user-events"
        
        resources:
          requests:
            memory: "650Mi"
            cpu: "75m"
          limits:
            memory: "1Gi"
            cpu: "700m"
            
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 90
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: product-service-config

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: sangsangplus-backend
  labels:
    app: product-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
    name: http
  selector:

    app: product-service

