apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: product-service
type: Opaque
data:
  db-username: c2FuZ3NhbmdwbHVzX2FkbWlu  # sangsangplus_admin (base64)
  db-password: ZWtkbWExNDQzIQ==  # ekdma1443! (base64)
  jwt-secret: VlFvdExYV3ZzcFVkb2FnRnMyam1WaVhIMGdKWDRqRUllODVLSW9GT0RDRT0=