apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: sangsangplus
  labels:
    app: product-service
spec:
  type: ClusterIP
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: product-service